[project]
name = "mtg-collections"
version = "0.1.0"
description = "MTG card collection and deck service"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.4",
    "requests>=2.32.4",
]
